apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd
resources:
- ../../base
- backup.yaml
- configmap.yaml
- route.yaml
- sealed-secret.yaml
images:
- digest: sha256:14261041103fd7c2bc1f8963c496cac3e60def843ffc630b511e2a2467660aea
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:13bfbbc7ceb73dfdc041db7d178a4108df3d61c0e02c313cd055a3ac27a943c0
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
