apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd
resources:
- ../../base
- backup.yaml
- configmap.yaml
- route.yaml
- sealed-secret.yaml
images:
- digest: sha256:eb57162310631667ba411d356eb91f3664ae23a61ff1662ef6f5df6f9ae82919
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:fe35edc2633894d9d9e06c6e067c5deda9ddf2cf247f0702ee45d197dff9b259
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
