apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd
resources:
- ../../base
- backup.yaml
- configmap.yaml
- route.yaml
- sealed-secret.yaml
images:
- digest: sha256:0592d28fe7e8c15fc839a8cdd9e23b677a7d049c2f12b4f5a51fca18206b5193
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:621dab0ec5cc85c6fb30d6967ff09229de2ea5e939ccccc3980bbe3a094f5457
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
