---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ai-read-access
  namespace: pvdd
spec:
  encryptedData:
    AI_READ_ACCESS_EMAIL: AgBTmaH4C3Rx5SztSJJL9MC7ehRCAM+BnDWM2szb/TpTVN+b+fDSX8TdZ9JigJaT/lzK1Hn1dadLFPyB7QggCicT0qRI8Igh/xAny6XjW9DdaCBH+gI/jmZdIxisbtC8RtC58BwuF+JdQPwSKnxQPcyH+cXbZ9UL1nrcAIC5h3bCDgbwLaKjSxYMavqnR8SyGBw0LlsV+RZ8Db60JcFpi6Gsbtf2zDnXWVU/W9tWz/0XZNP7gs5dmpYVmFJyDtSj40zDGQ2KcyiZnM5nDI/v8v1yRzBPurVQFBRCc1UVOkVndgIknzOJBasLTt0KWUar7VKGGRDEU1E7cuXiWpQy99bVu8r8DrYBrUe6FwD7/HFw+zWiDOmFyUGVfaJUHosbi8CD+t5NFLnbMOB+xBQlfLjdKjdOq7WoO6AkvkubfTltw4p9lZXgmYBy7uPSSO1kUe4HTSGeYVp1q9w+XFCnOI/EvOovXOaiqYqNz5pX59T28HE9COVUIcVo14ZNu29THvB/UDMu92eCRQIiNUNk6bidbGAwThKcyaKbWYfsT9lYE2z4ADkK4aiZ7vPdk5vT05+F0nDET1Izu1LVdzPBADjv3qPDL9QIdrf4ZAtib+aRSHgqJyAAUROkXrhblm1zEN9dNP6JN4xMEza6JZ4fxLIxtZvoFwCbd7kR/pEP2IPsjsopQmTmsukQqgqitUvNhDsoNXPn5mVZex1c14f32dYvx+flxdBV
    AI_READ_ACCESS_TOKEN: AgB4O42BoXTap7n/gCBrJvVZiay0peWF++Oe7nZl2HIlOaGNZE6r8/eW2kXXjVStQXXOR3qxDCfNMqX1Kp+SUAtaJzYcltONz01fKN3WVeeL8C9++DNCmrv49X9ZQLoeUaC5Hp3OkVnkc6JXeD4KHzZNQwMnjZdKHaZPpOyQKcOeLwmbx19AWlGeKn34vIV77aQkPBD8jrR8hP3JG1p5Y6UKFFn0W091kT59PtoOpCCxSKs0yqY4aX//98LQpPkwKdDuRaaoZYPS4pHlcHUwsnMsLP+zUg345rbVvfwiS8qkF5/n43gr+pZtSlxOvL4jFsu9rVPzp0tVw9ljKdCHDPeP7uyF2eBSJ2ldZVYIHN8fNXca0hpOT13Kl5RC9jCSrnAlGnYuFuTuz94UnUPA8n0+SZM7GGxPEdR5OuylyEkYCz1UfOGoyOfxix6uiqRpuXKOWSxHm/R86yucrlJ9HyFZaBa4RJYj9L3sYeIXjkO/XwXxmjiaJ8KjWX8W7+rItmRwGhp1u6BFmd3Of95Pc8J4qOGY1DN88XNZwuKrc+4YnKO64GTELpui8AFPDiKPAeTPcyV0N+FHNki9uE9cwrQ6LLgnZ8f8qwMXmf0gIYx6+ptasOhhkTBTCvEgcWUojUZk15nEpV8AbNPqxTSefAiZIJMEP2sdqDeoCGR68LlPmOpSJPtK0kGnyeqQd2QyFJdV/rXA6ADiIAIssO4/IEjfPRFwVe4dp+MGZISaOYF8hjV7GDb8Nh86qRZnx8qfIW4wt1N3DvxcFcrsbhRRyMt1
  template:
    metadata:
      name: ai-read-access
      namespace: pvdd
    type: Opaque
