apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd-acceptance
resources:
- ../../base
- configmap.yaml
- mock.yaml
- route.yaml
- sealed-secret.yaml
images:
- digest: sha256:1543a4abe46396b28f2b9bc3080c64f78204fab27ffb3a7128e4181bbad8e5d1
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:c7318b7e9dbdbdcb0ff86db3b8b830f197d2f291e9e331e1dee3f42e0fc2f720
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
- digest: sha256:e879dadc5b4fb93502178a30b0cb61e9300661fac8946675ffdf06f8ca8060bd
  name: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
  newName: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
