apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd-acceptance
resources:
- ../../base
- configmap.yaml
- mock.yaml
- route.yaml
- sealed-secret.yaml
images:
- digest: sha256:b8424696c84ec62d248bd1fa16007fffa377cfb1f7591b5a7913d74a3eaa6a83
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:d658fefe3d61a1bfcc472f508894c98a7b14d31e57bba2e6a936bd0b020b41c9
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
- digest: sha256:3ab1ea5053db36ad1f77d5f9ab55a734e8fb06b39907e44f2a24bd7bcc7e6b13
  name: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
  newName: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
