apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pvdd-acceptance
resources:
- ../../base
- configmap.yaml
- mock.yaml
- route.yaml
- sealed-secret.yaml
patches:
- patch: |-
    - op: remove
      path: /spec/encryptedData/PVDD_GOOGLE_CLIENT_ID
  target:
    kind: SealedSecret
    name: pvdd-secrets
images:
- digest: sha256:34954968053533053ff38e9d222909f4b0dfeab35a68a3d2cb0a4825cc203fe5
  name: ghcr.io/robbertvdzon/pvdd-backend
  newName: ghcr.io/robbertvdzon/pvdd-backend
- digest: sha256:bcb261e84cf5ddf01bbf38c886195a1c6b86effbd6f1101c94380dd34eefcb22
  name: ghcr.io/robbertvdzon/pvdd-frontend
  newName: ghcr.io/robbertvdzon/pvdd-frontend
- digest: sha256:d7cbe52c2f5cd115c41c96256601e0e2ded92bf2814c9a8fee7030d0bc6e178b
  name: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
  newName: ghcr.io/robbertvdzon/pvdd-meeting-source-mock
