apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pvdd
spec:
  host: pvdd-acceptance.vdzonsoftware.nl
  to: {kind: Service, name: frontend}
  port: {targetPort: http}
  # Cloudflare houdt de externe verbinding HTTPS en benadert de interne Route via HTTP.
  tls: {termination: edge, insecureEdgeTerminationPolicy: Allow}
